version: '3'
services:
  wp:
    build: .
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: secret
    volumes:
      - ./site:/var/www/html
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
    volumes:
      - ./db:/var/lib/mysql
